language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
dist: trusty
install:
  - pip install .
  - pip install coverage
  - pip install coveralls
  - pip install flake8
script:
  - flake8 --ignore E501,E722
  - coverage run --source=configbutler/ setup.py test
after_script:
  - coverage report
after_success:
  - coveralls